export const ERROR = 'ERROR';
export const LOADER = 'LOADER';

export const GET_PRODUCT_DATA = 'GET_PRODUCT_DATA';
export const LOAD_PRODUCT_DATA = 'LOAD_PRODUCT_DATA';

export const POST_PRODUCT_DATA = 'POST_PRODUCT_DATA';
export const LOAD_POST_PRODUCT_DATA = 'LOAD_POST_PRODUCT_DATA';

export const UPDATE_PRODUCT_DATA = 'UPDATE_PRODUCT_DATA';
export const LOAD_UPDATE_PRODUCT_DATA = 'LOAD_UPDATE_PRODUCT_DATA';

export const DELETE_PRODUCT_DATA = 'DELETE_PRODUCT_DATA';
export const LOAD_DELETED_PRODUCT_DATA = 'LOAD_DELETED_PRODUCT_DATA';